### ISSUE TITLE
Support NRT indexing and archiving 

### ISSUE THREAD

**Issue by whatnick** [GeoscienceAustralia/dea-airflow#1]
Add DAG's based on [Airflow K8S operator](https://airflow.readthedocs.io/en/latest/howto/operator/kubernetes.html) to trigger the following containers to perform actions.

- Implement Thredds / S3 Crawler : https://hub.docker.com/r/opendatacube/datacube-index
- Implement Orchestrate archive, explorer summarise, ows update_ranges : https://hub.docker.com/r/geoscienceaustralia/dea-k8s-data

The DAG's should be parameterisable by similar parameters to what current k8s jobs/cronjobs/python scheduler embedded in container approach uses.

**Comment by alexgleith** [comment]
From the Slack discussion, as we implement these DAGs, I think *starting* with consistent naming is really important.

This is a great opportunity to do things better and keep it clean as we go.

I'm happy to help with building Docker images. I've automated two of them now, happy to poke away at more.

**Comment by omad** [comment]
Also more than happy to help with the implementation, ask me anything airflowy :)
